In [31]:
#-------------------------------------------------------------------------------------------------------------------------------
import pandas as pd                                                 # Importing for panel data analysis
from pandas_profiling import ProfileReport                          # Import Pandas Profiling (To generate Univariate Analysis) 
pd.set_option('display.max_columns', None)                          # Unfolding hidden features if the cardinality is high      
pd.set_option('display.max_colwidth', None)                         # Unfolding the max feature width for better clearity      
pd.set_option('display.max_rows', None)                             # Unfolding hidden data points if the cardinality is high
pd.set_option('mode.chained_assignment', None)                      # Removing restriction over chained assignments operations
pd.set_option('display.float_format', lambda x: '%.5f' % x)         # To suppress scientific notation over exponential values
#-------------------------------------------------------------------------------------------------------------------------------
import numpy as np                                                  # Importing package numpys (For Numerical Python)
#-------------------------------------------------------------------------------------------------------------------------------
import matplotlib.pyplot as plt                                     # Importing pyplot interface using matplotlib
from matplotlib.pylab import rcParams                               # Backend used for rendering and GUI integration                                               
import seaborn as sns                                               # Importin seaborm library for interactive visualization
%matplotlib inline
#-------------------------------------------------------------------------------------------------------------------------------
from sklearn.metrics import accuracy_score                          # For calculating the accuracy for the model
from sklearn.metrics import precision_score                         # For calculating the Precision of the model
from sklearn.metrics import recall_score                            # For calculating the recall of the model
from sklearn.metrics import precision_recall_curve                  # For precision and recall metric estimation
from sklearn.metrics import confusion_matrix                        # For verifying model performance using confusion matrix
from sklearn.metrics import f1_score                                # For Checking the F1-Score of our model  
from sklearn.metrics import roc_curve                               # For Roc-Auc metric estimation
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
#-------------------------------------------------------------------------------------------------------------------------------
from sklearn.model_selection import train_test_split                # To split the data in training and testing part     
from sklearn.linear_model import LogisticRegression                 # To create the Logistic Regression Model
#-------------------------------------------------------------------------------------------------------------------------------
import warnings                                                     # Importing warning to disable runtime warnings
warnings.filterwarnings("ignore")                                   # Warnings will appear only once

In [17]:
# Read train data
customer_data = pd.read_csv("c:/existing_base_train.csv")
#dftrain.shape
#dftrain.describe
customer_data.head()


REF_NO children age_band   status         occupation occupation_partner  \
0    5466        2    31-35  Partner       Professional       Professional   
1    9091     Zero    45-50  Partner  Secretarial/Admin       Professional   
2    9744        1    36-40  Partner      Manual Worker      Manual Worker   
3   10700        2    31-35  Partner      Manual Worker      Manual Worker   
4    1987     Zero    55-60  Partner          Housewife       Professional   

      home_status      family_income self_employed self_employed_partner  \
0        Own Home           >=35,000            No                    No   
1        Own Home           >=35,000            No                    No   
2  Rent Privately  <22,500, >=20,000           Yes                   Yes   
3        Own Home  <25,000, >=22,500            No                    No   
4        Own Home           >=35,000            No                    No   

   year_last_moved       TVarea post_code post_area  \
0             1981     Meridian   M51 0GU       M51   
1             1997     Meridian   L40 2AG       L40   
2             1996          HTV  TA19 9PT      TA19   
3             1990  Scottish TV   FK2 9NG       FK2   
4             1989    Yorkshire  LS23 7DJ      LS23   

   Average_Credit_Card_Transaction  Balance_Transfer  Term_Deposit  \
0                         26.98000          29.99000     312.25000   
1                         35.98000          74.48000       0.00000   
2                          0.00000          24.46000       0.00000   
3                         44.99000           0.00000       0.00000   
4                          0.00000           0.00000       0.00000   

   Life_Insurance  Medical_Insurance  Average_A/C_Balance  Personal_Loan  \
0       299.79000           88.72000            108.85000      175.43000   
1        99.96000           10.99000             48.45000       15.99000   
2        18.44000            0.00000              0.00000        0.02000   
3         0.00000           29.99000              0.00000        0.00000   
4         0.00000            0.00000              0.00000        0.00000   

   Investment_in_Mutual_Fund  Investment_Tax_Saving_Bond  Home_Loan  \
0                  134.35000                     8.98000   55.44000   
1                    0.00000                     0.00000    0.00000   
2                   10.46000                     0.00000    0.00000   
3                    0.00000                     0.00000    0.00000   
4                    9.98000                     0.00000    0.00000   

   Online_Purchase_Amount  gender      region  Investment_in_Commudity  \
0                 7.68000  Female  North West                151.55000   
1                18.99000  Female  North West                 44.28000   
2                 0.00000  Female  South West                  8.58000   
3                 0.00000  Female    Scotland                 15.00000   
4                 0.00000  Female     Unknown                  0.00000   

   Investment_in_Equity  Investment_in_Derivative  Portfolio_Balance  \
0              81.79000                 136.02000          360.37000   
1              13.91000                  29.23000           89.22000   
2               1.75000                   4.82000           14.50000   
3               0.00000                   5.00000           68.98000   
4               1.66000                   1.66000            1.88000   

   Revenue_Grid  
0             2  
1             2  
2             2  
3             2  
4             2

In [18]:
customer_data.describe(include='all')


REF_NO children age_band   status    occupation  \
count   8124.00000     8124     8124     8124          8124   
unique         nan        5       13        5             9   
top            nan     Zero    45-50  Partner  Professional   
freq           nan     4991     1098     6124          1949   
mean    5797.34330      NaN      NaN      NaN           NaN   
std     3322.49757      NaN      NaN      NaN           NaN   
min        2.00000      NaN      NaN      NaN           NaN   
25%     2924.75000      NaN      NaN      NaN           NaN   
50%     5811.50000      NaN      NaN      NaN           NaN   
75%     8681.50000      NaN      NaN      NaN           NaN   
max    11518.00000      NaN      NaN      NaN           NaN   

       occupation_partner home_status family_income self_employed  \
count                8124        8124          8124          8124   
unique                  9           5            13             2   
top               Unknown    Own Home      >=35,000            No   
freq                 1942        7506          2014          7543   
mean                  NaN         NaN           NaN           NaN   
std                   NaN         NaN           NaN           NaN   
min                   NaN         NaN           NaN           NaN   
25%                   NaN         NaN           NaN           NaN   
50%                   NaN         NaN           NaN           NaN   
75%                   NaN         NaN           NaN           NaN   
max                   NaN         NaN           NaN           NaN   

       self_employed_partner  year_last_moved   TVarea post_code post_area  \
count                   8124       8124.00000     8124      8124      8124   
unique                     2              nan       14      8050      1937   
top                       No              nan  Central   DT4 0LN       PR5   
freq                    7207              nan     1294         2        28   
mean                     NaN       1967.87691      NaN       NaN       NaN   
std                      NaN        182.56379      NaN       NaN       NaN   
min                      NaN          0.00000      NaN       NaN       NaN   
25%                      NaN       1978.00000      NaN       NaN       NaN   
50%                      NaN       1988.00000      NaN       NaN       NaN   
75%                      NaN       1994.00000      NaN       NaN       NaN   
max                      NaN       1999.00000      NaN       NaN       NaN   

        Average_Credit_Card_Transaction  Balance_Transfer  Term_Deposit  \
count                        8124.00000        8124.00000    8124.00000   
unique                              nan               nan           nan   
top                                 nan               nan           nan   
freq                                nan               nan           nan   
mean                           23.25109          46.08292      27.28465   
std                            51.14750          79.08469      54.13354   
min                             0.00000           0.00000       0.00000   
25%                             0.00000           0.00000       0.00000   
50%                             0.00000          17.48500       0.00000   
75%                            23.48000          64.99000      34.49000   
max                           662.26000        2951.76000     784.82000   

        Life_Insurance  Medical_Insurance  Average_A/C_Balance  Personal_Loan  \
count       8124.00000         8124.00000           8124.00000     8124.00000   
unique             nan                nan                  nan            nan   
top                nan                nan                  nan            nan   
freq               nan                nan                  nan            nan   
mean          65.31794           18.82620             31.83802       25.41583   
std           95.76245           32.02233             45.24944       85.13015   
min            0.0000

In [6]:
# Upgrading pandas profiling to the latest version
!pip install pandas-profiling

In [19]:
profile =ProfileReport(customer_data,title = "dfTrain Profiling")
profile.to_file(output_file="customer_profiling_before_preprocessing1.html")


In [40]:
# Convert customer data into Dataframe
customer_data = customer_data.drop(['REF_NO','self_employed','self_employed_partner','post_code','post_area'], axis=1)
df = pd.DataFrame(customer_data) 
df.head()
df.shape

KeyError: "['REF_NO' 'self_employed' 'self_employed_partner' 'post_code' 'post_area'] not found in axis"

In [41]:
# Creating dummy variables
df = df.drop('region', axis=1) 
df = pd.get_dummies(df) 
df.head()
df.shape


KeyError: "['region'] not found in axis"

In [22]:
df.shape

(8124, 93)

In [23]:
# Spliting data in train test for modeling 
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(df, df.Revenue_Grid, test_size=0.25, random_state = 0)
x_train = x_train.drop('Revenue_Grid', 1) 
x_test = x_test.drop('Revenue_Grid', 1)


In [24]:
# Declaring LR
from sklearn.linear_model import LogisticRegression
# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()

In [25]:
# Running model to fit training dataset
logisticRegr.fit(x_train, y_train)

LogisticRegression()

In [26]:
# Predictions using test dataset
predictions = logisticRegr.predict(x_test)
print(predictions)

[2 1 1 ... 2 2 2]


In [27]:
# Use score method to get accuracy of model
score = logisticRegr.score(x_test, y_test)
print('Accuracy of the Model: (in percentage)')
print(score*100)

Accuracy of the Model: (in percentage)
93.69768586903004


In [32]:
# Confusion Matrix
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

[[ 148   79]
 [  49 1755]]


In [33]:
# f1 score on trained model
f1_score(y_test,predictions, average=None)

array([0.69811321, 0.96481583])

In [43]:
# Apply model on test data to get results to submit
test_data = pd.read_csv("c:/existing_base_test.csv")
df_test = pd.DataFrame(test_data)
df_test_id = pd.DataFrame(test_data)
df_test = df_test.drop(['REF_NO','self_employed','self_employed_partner','post_code','post_area'], axis = 1)

In [44]:
# Create dummy variables
df_test = df_test.drop('region', axis=1) 
df_test = pd.get_dummies(df_test)
df_test.head()
df_test.shape

(2031, 92)

In [45]:
# Apply prediction to get results
predictions = logisticRegr.predict(df_test)
print(predictions)

[2 2 2 ... 1 1 2]


In [46]:
predictions = pd.DataFrame(predictions, columns=['predictions'])
predictions.head()

predictions
0            2
1            2
2            2
3            2
4            2

In [47]:
# Preparing results using column REF_NO
df_test_id = df_test_id[['REF_NO']]
df_test_id.head()

REF_NO
0     697
1    7897
2    4729
3    6914
4    2795

In [49]:
# Concat df to get results to submit
sample_resut = pd.concat([df_test_id, predictions],axis=1)

In [50]:
sample_resut.head()

REF_NO  predictions
0     697            2
1    7897            2
2    4729            2
3    6914            2
4    2795            2

In [53]:
print(sample_resut.to_csv(index=False, header=False))

697,2
7897,2
4729,2
6914,2
2795,2
7367,2
9598,2
6704,2
4933,2
9880,2
1083,2
8100,1
109,2
4792,2
3226,2
2019,2
2165,2
9551,2
1759,2
576,2
340,2
3726,2
40,2
4180,2
5399,2
3600,2
4715,2
8744,2
2086,2
10447,2
353,2
1339,2
9549,2
9364,2
6230,2
1200,2
497,2
9625,2
7402,2
1921,2
3467,1
3377,2
8251,2
187,2
11043,2
552,2
8099,2
9647,2
9812,1
6943,2
2500,2
4640,2
6997,2
4219,2
9300,1
5906,2
1844,2
3785,1
1673,2
8674,2
2426,2
4414,2
6494,2
6490,2
4649,2
2649,2
9338,2
4473,2
5326,2
11306,2
701,2
5756,2
1659,2
6962,2
419,2
8463,1
10429,2
9070,2
9737,2
10373,2
768,2
1818,2
10289,2
6889,2
2718,2
737,2
5417,2
9728,2
9504,2
10280,2
9493,2
1162,2
6912,2
4509,2
6356,2
4049,2
5810,2
8906,2
8807,2
9839,2
3522,2
6835,2
5639,2
9206,2
121,2
1853,1
1832,2
7611,2
6671,1
4774,2
10740,2
11345,2
2159,2
8237,2
2646,2
5494,2
11402,2
4383,2
7637,2
9896,2
3956,2
7586,2
508,2
4811,2
586,1
5979,2
1354,2
3573,2
7868,2
3758,2
1092,2
10596,1
10563,2
1230,2
1316,2
10547,2
6070,2
2431,2
2880,2
360,2
11194,2
5984,2
7494,2
570